'use strict';
// Writes docs/THROUGHLINE_AUDIT.md: one row per hypothesis card, with the problem flags.
// Run: node scripts/throughline_audit.js   (rules are in the RULES list below)
const fs = require('fs'), path = require('path'), E = require('../hyp-eval.js');
const root = path.join(__dirname, '..');
const names = fs.readdirSync(path.join(root, 'hypotheses')).filter(f => /^h\d{3}-.*\.json$/.test(f)).sort();
const cache = {}; const load = s => cache[s] || (cache[s] = JSON.parse(fs.readFileSync(path.join(root, s))));
const RULES = [
  ['title', 'Title is not a question', c => !/\?\s*$/.test(c.title)],
  ['why', 'No `why` field', c => !c.why],
  ['limit', 'Has a caveat that renders only inside details', c => (c.caveats || []).length > 0],
  ['explore', 'Caveats, expect or rules text says exploratory or set after seeing data', c => /exploratory|set after|after (seeing|earlier)|saved after/i.test(JSON.stringify([c.caveats, c.expect, c.rules]))],
  ['archive', 'Monthly or history source, so the page says "full archive"', c => /history|monthly/.test(c.check.source + ' ' + (c.check.path || ''))],
  ['match', 'A caveat says matches are words, so copy could read as adoption', c => (c.caveats || []).some(x => /match/i.test(x))],
  ['refresh', 'Verdict is refuted or inconclusive, so a refresh can contradict static copy', (c, r) => r.verdict !== 'supported'],
];
const rows = names.map(n => {
  const c = JSON.parse(fs.readFileSync(path.join(root, 'hypotheses', n)));
  const r = E.evaluate(c, load(c.check.source));
  const f = RULES.map(([, , fn]) => fn(c, r) ? 1 : 0);
  return { c, r, f };
});
const out = ['# Throughline audit', '', 'Generated by `node scripts/throughline_audit.js` from `hypotheses/*.json` and `hyp-eval.js`. Do not edit by hand. Issue #126, epic #125.', '', `Cards: ${rows.length}. Verdicts: ` + ['supported', 'refuted', 'inconclusive'].map(v => rows.filter(x => x.r.verdict === v).length + ' ' + v).join(', ') + '.', '', '## Problem counts', '', '| Flag | Rule | Cards |', '|---|---|---|'];
RULES.forEach(([k, d], i) => out.push(`| ${k} | ${d} | ${rows.filter(x => x.f[i]).length} of ${rows.length} |`));
const tbl = rs => { const o = ['| Card | Audience | Verdict | Title | ' + RULES.map(x => x[0]).join(' | ') + ' |', '|---|---|---|---|' + RULES.map(() => '---').join('|') + '|']; rs.forEach(x => o.push(`| ${x.c.id} | ${x.c.audience || 'none'} | ${x.r.verdict} | ${x.c.title.replace(/\|/g, '/')} | ` + x.f.map(v => v ? 'x' : '').join(' | ') + ' |')); return o; };
const weak = rows.filter(x => x.r.verdict !== 'supported');
out.push('', `## Refuted or inconclusive cards (${weak.length})`, '', ...tbl(weak), '', `## All cards (${rows.length})`, '', ...tbl(rows), '');
fs.writeFileSync(path.join(root, 'docs/THROUGHLINE_AUDIT.md'), out.join('\n'));
console.log(rows.length, weak.length);
